#!/bin/bash
# Generate .env.cloud from Terraform outputs. Run after `terraform apply`.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "${REPO_ROOT}/infrastructure"

if ! terraform output -raw lakehouse_bucket_name >/dev/null 2>&1; then
  echo "ERROR: terraform state not found or empty. Run 'terraform apply' first." >&2
  exit 1
fi

BUCKET="$(terraform output -raw lakehouse_bucket_name)"
BROKERS="$(terraform output -raw msk_bootstrap_brokers)"

OUT="${REPO_ROOT}/.env.cloud"
{
  echo "# Generated by scripts/generate_cloud_env.sh — DO NOT EDIT BY HAND"
  echo "PT_LAKEHOUSE_BASE=s3://${BUCKET}"
  echo "PT_KAFKA_BOOTSTRAP=${BROKERS}"
  echo "PT_SPARK_MASTER=yarn"
  echo "PT_GLUE_ICEBERG_WAREHOUSE=s3://${BUCKET}/iceberg/warehouse"
  echo "PT_ENVIRONMENT=cloud"
  echo "PT_SHUFFLE_PARTITIONS=200"
  echo "PT_MAX_OFFSETS_PER_TRIGGER=50000"
  echo "PT_WATERMARK_DELAY=10 minutes"
} > "${OUT}"

echo "Generated ${OUT}"
